###### Starts by Importing Numpy Package ,this package is also called a numeric Python

In [1]:
import numpy as np

###### Drawback of regular python list is shown below ,it does not support operations like ** in the list

In [4]:
weights =[90,80.50,89,56,95.60]
heights =[1.86,1.98,1.45,1.75,1.65]
bmi = weights/heights **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

###### This is why we use numpy to use operations on the arrays

In [8]:
weights =[90,80.50,89,56,95.60]
heights =[1.86,1.98,1.45,1.75,1.65]
np_weights = np.array(weights)
np_heights = np.array(heights)
bmi = np_weights/np_heights **2
print(bmi)

[ 26.01456816  20.53361902  42.33055886  18.28571429  35.11478421]


###### type of the numpy variable is 

In [10]:
print(type(np_weights),type(bmi))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


###### Difference between list and numpy array 

In [17]:
list_1 = [1,2,3,4,"5"]
np_1 = np.array(list_1)
np_2 = np.array([1,2,3,4,5])
print("Type of list can contain different types",type(list_1))
print("Data Type of numpy is converted to same types",np_1.dtype)
print("Data Type of numpy will be of  same types",np_2.dtype)

Type of list can contain different types <class 'list'>
Data Type of numpy is converted to same types <U21
Data Type of numpy will be of  same types int64


###### Summation of list and numpy is different

In [20]:
list_1 = [1,2,3,4,5,6]
list_1 + list_1 #appended in the list 

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [21]:
np_1 = np.array([1,2,3,4,5])
np_1 + np_1 #summed up 

array([ 2,  4,  6,  8, 10])

###### fetching data from array 

In [25]:
print(bmi[0]) #index starts with 0
print(bmi[1]) #fetch based on index

20.5336190185
26.0145681582


In [26]:
bmi>25 #this will return the boolean value of the array 

array([ True, False,  True, False,  True], dtype=bool)

In [27]:
bmi[bmi>25] #now fetch the actual values of the bmi and the return type is array

array([ 26.01456816,  42.33055886,  35.11478421])

###### sorting of array 

In [47]:
temp = np.random.randint(1,10, 10)
np.sort(temp) #sorting ascending

array([1, 2, 2, 4, 4, 5, 6, 7, 7, 8])

In [48]:
(-np.sort(-temp)) #sorting descending

array([8, 7, 7, 6, 5, 4, 4, 2, 2, 1])

In [49]:
np.sort(temp)[::-1] #[::-1] is just reversing the orignal string 

array([8, 7, 7, 6, 5, 4, 4, 2, 2, 1])

In [53]:
np.sort(temp)[::-1][1] #fetch the first element after sorting the element 

7

###### add,delete and drop the element from the numpy array

In [26]:
np_add = np.random.randint(1,10,10) #create a random array of numpy
print(np_add)

[9 1 4 7 9 9 8 5 9 3]


In [27]:
np.delete(np_add,1,axis=0) #deleteing based on the index ,axis will be default =0 for 1 D array 

array([9, 4, 7, 9, 9, 8, 5, 9, 3])

In [29]:
np.insert(np_add,0,3,axis=0) #insert element at any specific index ,axis will be default =0 for 1 D array 

array([3, 9, 1, 4, 7, 9, 9, 8, 5, 9, 3])

In [30]:
np.append(np_add,[1],axis=0) # append array to the existing array

array([9, 1, 4, 7, 9, 9, 8, 5, 9, 3, 1])

###### find the index of element in the numpy array 

In [43]:
print(np.where(np_add==5))

(array([7]),)


In [48]:
np.nonzero(np_add-5==0)

(array([7]),)

In [52]:
np_add==5

array([False, False, False, False, False, False, False,  True, False, False], dtype=bool)

###### count,sum of element in array 

In [62]:
np_agg = np.random.randint(1,10,15) #create a random array of numpy
np_agg

array([7, 8, 4, 7, 4, 8, 3, 5, 5, 8, 7, 8, 2, 5, 8])

In [55]:
np_agg.sum()

23

In [56]:
np_agg.mean()

4.5999999999999996

In [58]:
np_agg.prod()

648

In [60]:
np_agg.std()

2.7276363393971712

In [67]:
values, counts = np.unique(np_agg, return_counts=True) #return the count of repetition of element in an array 
dict(zip(values, counts))

{2: 1, 3: 1, 4: 2, 5: 3, 7: 3, 8: 5}

###### Basics of numpy

In [10]:
np_dim1 = np.array([1,2,3,4]) #only one dimentions of the array

In [17]:
print(np_dim1.ndim) #give the number of axis of the array ,for this case it will return 1
print(np_dim2.itemsize) #number of element in the array

1
8


In [13]:
np_dim2 = np.array([[1,2,3,4],[2,3,4,5]]) #only one dimentions of the array

In [18]:
print(np_dim2.ndim) #give the number of axis of the array ,for this case it will return 2
print(np_dim2.itemsize) #number of element in the array
print(np_dim2.data)

2
8


In [19]:
#empty(shape[, dtype, order])	Return a new array of given shape and type, without initializing entries.
np.empty([2, 2])

array([[  4.94065646e-324,   9.88131292e-324],
       [  1.48219694e-323,   1.97626258e-323]])

In [22]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)]) 
print(x)

[[ 1.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j]
 [ 1.+1.j  3.+0.j]]


In [23]:
np.zeros((2, 3))#creating numpy with zero values 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [125]:
np.ones((2,4))#creating shapes with 1's

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [127]:
np.eye(3)#creating a 3x3 array with 1 in diagonal

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [133]:
y=np.arange(3)
np.diag(y)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [137]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [140]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [142]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [144]:
np.vstack([p,2*p])#Use vstack to stack arrays in sequence vertically (row wise).

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [147]:
np.hstack([p, 2*p])#Use hstack to stack arrays in sequence horizontally (column wise).

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [151]:
x = np.arange(3)
y = np.arange(3)
x.dot(y)

5

In [160]:
z = np.array([y, y**2])
len(z)
z

array([[0, 1, 2],
       [0, 1, 4]])

In [164]:
z.T#transpose 

array([[0, 0],
       [1, 1],
       [2, 4]])

In [167]:
z.dtype

dtype('int64')

In [169]:
z=z.astype('f') #change datatype to float of an array
z.dtype

dtype('float32')

In [175]:
s=np.arange(10) #this will create array with regular increment values 
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
print(s.argmax(),s.argmin())

9 0


In [178]:
np_rand=np.random.randint(1,10,(4,3))#Let's create a new 4 by 3 array of random numbers 0-9.
np_rand

array([[1, 1, 2],
       [9, 5, 5],
       [9, 1, 8],
       [1, 7, 7]])

In [27]:
np.arange(2, 10, dtype=np.float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [28]:
np.arange(2, 3, 0.1)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9])

In [29]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

###### Indexing in Numpy

In [33]:
x = np.arange(10)
print(x[2])
print(x[-2])
x

2
8


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
print(x[1,3])
print(x[1][3]) #one of the same thing

8
8


In [40]:
x[1,-1]#fetch data of the axis 1 and fetch the -1 element from it

9

In [43]:
 x[0] #fetch the data from axis 0

array([0, 1, 2, 3, 4])

###### Other indexing options

In [45]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x[2:5]

array([2, 3, 4])

In [47]:
x[:-7]

array([0, 1, 2])

In [48]:
x[-7:]

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
y = np.arange(49).reshape(7,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [68]:
y[1:7:2] #where 1 represent start from axis 1 ,till axis 7 and steps by 2

array([[ 7,  9, 11, 13],
       [21, 23, 25, 27],
       [35, 37, 39, 41]])

In [72]:
y[1:7:2,::3] #before comma represents rows and after columns [start index:till which axis:steps]

array([[ 9, 12],
       [23, 26],
       [37, 40]])

In [80]:
x=np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [81]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [84]:
x[np.array([3, -3, 1, 8])]

array([7, 4, 9, 2])

In [83]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

In [87]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [88]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [89]:
y[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [90]:
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [91]:
 y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [92]:
y>20

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [93]:
y[y>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [101]:
b=y>20
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [122]:
x = np.arange(30).reshape(2,3,5) #5 element in each list of group of 3 list and total 2 list 
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [124]:
x.resize(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [106]:
 b = np.array([[True, True, False], [False, True, True]])

In [107]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

###### combining indexes with slices

In [110]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [108]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [109]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

###### Structural Indexing tool

In [111]:
y.shape

(5, 7)

In [112]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [114]:
y[:,np.newaxis,:]#the np.newaxis object can be used within array indices to add new dimensions with a size of 1

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [119]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [121]:
x[:,np.newaxis]+ x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

###### iterating over arrays

In [179]:
test = np.random.randint(0, 10, (4,3))
test

array([[5, 7, 0],
       [4, 2, 3],
       [6, 9, 2],
       [9, 5, 6]])

In [180]:
for row in test:
    print(row)

[5 7 0]
[4 2 3]
[6 9 2]
[9 5 6]


In [182]:
for i in range(len(test)):
    print(test[i])

[5 7 0]
[4 2 3]
[6 9 2]
[9 5 6]


In [183]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 7 0]
row 1 is [4 2 3]
row 2 is [6 9 2]
row 3 is [9 5 6]


In [184]:
test2 = test**2 
test2

array([[25, 49,  0],
       [16,  4,  9],
       [36, 81,  4],
       [81, 25, 36]])

In [185]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[5 7 0] + [25 49  0] = [30 56  0]
[4 2 3] + [16  4  9] = [20  6 12]
[6 9 2] + [36 81  4] = [42 90  6]
[9 5 6] + [81 25 36] = [90 30 42]
