###### Starts by Importing Numpy Package ,this package is also called a numeric Python

In [2]:
import numpy as np

###### Drawback of regular python list is shown below ,it does not support operations like ** in the list

In [4]:
weights =[90,80.50,89,56,95.60]
heights =[1.86,1.98,1.45,1.75,1.65]
bmi = weights/heights **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

###### This is why we use numpy to use operations on the arrays

In [8]:
weights =[90,80.50,89,56,95.60]
heights =[1.86,1.98,1.45,1.75,1.65]
np_weights = np.array(weights)
np_heights = np.array(heights)
bmi = np_weights/np_heights **2
print(bmi)

[ 26.01456816  20.53361902  42.33055886  18.28571429  35.11478421]


###### type of the numpy variable is 

In [10]:
print(type(np_weights),type(bmi))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


###### Difference between list and numpy array 

In [17]:
list_1 = [1,2,3,4,"5"]
np_1 = np.array(list_1)
np_2 = np.array([1,2,3,4,5])
print("Type of list can contain different types",type(list_1))
print("Data Type of numpy is converted to same types",np_1.dtype)
print("Data Type of numpy will be of  same types",np_2.dtype)

Type of list can contain different types <class 'list'>
Data Type of numpy is converted to same types <U21
Data Type of numpy will be of  same types int64


###### Summation of list and numpy is different

In [20]:
list_1 = [1,2,3,4,5,6]
list_1 + list_1 #appended in the list 

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [21]:
np_1 = np.array([1,2,3,4,5])
np_1 + np_1 #summed up 

array([ 2,  4,  6,  8, 10])

###### fetching data from array 

In [25]:
print(bmi[0]) #index starts with 0
print(bmi[1]) #fetch based on index

20.5336190185
26.0145681582


In [26]:
bmi>25 #this will return the boolean value of the array 

array([ True, False,  True, False,  True], dtype=bool)

In [27]:
bmi[bmi>25] #now fetch the actual values of the bmi and the return type is array

array([ 26.01456816,  42.33055886,  35.11478421])

###### sorting of array 

In [47]:
temp = np.random.randint(1,10, 10)
np.sort(temp) #sorting ascending

array([1, 2, 2, 4, 4, 5, 6, 7, 7, 8])

In [48]:
(-np.sort(-temp)) #sorting descending

array([8, 7, 7, 6, 5, 4, 4, 2, 2, 1])

In [49]:
np.sort(temp)[::-1] #[::-1] is just reversing the orignal string 

array([8, 7, 7, 6, 5, 4, 4, 2, 2, 1])

In [53]:
np.sort(temp)[::-1][1] #fetch the first element after sorting the element 

7

###### add,delete and drop the element from the numpy array

In [26]:
np_add = np.random.randint(1,10,10) #create a random array of numpy
print(np_add)

[9 1 4 7 9 9 8 5 9 3]


In [27]:
np.delete(np_add,1,axis=0) #deleteing based on the index ,axis will be default =0 for 1 D array 

array([9, 4, 7, 9, 9, 8, 5, 9, 3])

In [29]:
np.insert(np_add,0,3,axis=0) #insert element at any specific index ,axis will be default =0 for 1 D array 

array([3, 9, 1, 4, 7, 9, 9, 8, 5, 9, 3])

In [30]:
np.append(np_add,[1],axis=0) # append array to the existing array

array([9, 1, 4, 7, 9, 9, 8, 5, 9, 3, 1])

###### find the index of element in the numpy array 

In [43]:
print(np.where(np_add==5))

(array([7]),)


In [48]:
np.nonzero(np_add-5==0)

(array([7]),)

In [52]:
np_add==5

array([False, False, False, False, False, False, False,  True, False, False], dtype=bool)

###### count,sum of element in array 

In [62]:
np_agg = np.random.randint(1,10,15) #create a random array of numpy
np_agg

array([7, 8, 4, 7, 4, 8, 3, 5, 5, 8, 7, 8, 2, 5, 8])

In [55]:
np_agg.sum()

23

In [56]:
np_agg.mean()

4.5999999999999996

In [58]:
np_agg.prod()

648

In [60]:
np_agg.std()

2.7276363393971712

In [67]:
values, counts = np.unique(np_agg, return_counts=True) #return the count of repetition of element in an array 
dict(zip(values, counts))

{2: 1, 3: 1, 4: 2, 5: 3, 7: 3, 8: 5}